apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-1-loadbalancer
spec:
  # For using an external load balancer. each service requires a LB.
  type: LoadBalancer

  selector:
    app: slow-api
  ports:
    - name: http
      port: 30003
      targetPort: 8000
      protocol: TCP
  
