apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-api-deployment
spec:
  selector:
    matchLabels:
      app: slow-api
  replicas: 1
  template:
    metadata:
      labels:
        app: slow-api
    spec:
      containers:
      - name: slow-api
        image: vhelsi/webinar-slow-api:2
        ports:
        - containerPort: 8000

